# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad017b5abe7a67a5028458d42a3eb4ad1eee0c2b6be06691ba77bc875c3fb98038e396bc3c7ebcfeaea069f8d64c1b14f33c4350beb55e6211279ec90d33de72

test:
  secret_key_base: df3fb4c2f57dd7f03b1faf497603f5c1fa952c95fa4a9e47393595aaffc4d457cd3dbf01528830fdc06083bcf182eeb105d14d56991b3bbf204a48446e2b86c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
